export const titles = [
  {
    id: 'last-signal',
    type: 'movie',
    title: 'The Last Signal',
    year: 2026,
    rating: '8.6',
    runtime: '2h 08m',
    duration: 128,
    genres: ['Sci-Fi', 'Mystery', 'Drama'],
    maturity: '16+',
    poster: '/art/poster-last-signal.jpg',
    backdrop: '/art/hero-last-signal.jpg',
    synopsis: 'At the edge of a silent ocean, radio astronomer Mara Vale catches a voice in the static — one that knows what happens tomorrow. The closer she gets to its source, the less certain she is about who is listening.',
    director: 'Nadia Calder',
    cast: ['Rhea Coleman', 'Daniel Kwan', 'Ari Lennox', 'Mika Reyes'],
    badge: 'VEYRA ORIGINAL',
  },
  {
    id: 'blue-hour',
    type: 'movie',
    title: 'Blue Hour',
    year: 2025,
    rating: '8.1',
    runtime: '1h 54m',
    duration: 114,
    genres: ['Drama', 'Romance'],
    maturity: '13+',
    poster: '/art/poster-blue-hour.jpg',
    backdrop: '/art/poster-blue-hour.jpg',
    synopsis: 'In the quiet minutes before the city wakes, two strangers find that the best things in life are often the ones we almost miss.',
    director: 'Elena Solis',
    cast: ['Nia James', 'Tomás Vela', 'Amara Okafor', 'Louis Bennett'],
    badge: 'NEW THIS WEEK',
  },
  {
    id: 'quiet-earth',
    type: 'movie',
    title: 'The Quiet Earth',
    year: 2026,
    rating: '8.8',
    runtime: '2h 01m',
    duration: 121,
    genres: ['Sci-Fi', 'Adventure'],
    maturity: '13+',
    poster: '/art/poster-quiet-earth.jpg',
    backdrop: '/art/poster-quiet-earth.jpg',
    synopsis: 'When the satellites go dark, a field scientist follows a strange green light into the mountains — and finds a world that may be waiting just for her.',
    director: 'Theo Park',
    cast: ['Mina Voss', 'Jamal Stone', 'Noah Ellis', 'Léa Fournier'],
    badge: 'TOP 10 FILMS',
  },
  {
    id: 'saltline',
    type: 'movie',
    title: 'Saltline',
    year: 2025,
    rating: '7.9',
    runtime: '1h 47m',
    duration: 107,
    genres: ['Thriller', 'Drama'],
    maturity: '16+',
    poster: '/art/poster-saltline.jpg',
    backdrop: '/art/poster-saltline.jpg',
    synopsis: 'A lighthouse keeper returns to her childhood island after a decade away. By morning, the tide has brought back something the village tried to forget.',
    director: 'Amir Laurent',
    cast: ['Sofia Nordin', 'Kai Okada', 'Owen Miles', 'Hana Idris'],
    badge: 'CRITICALLY LOVED',
  },
  {
    id: 'afterlight',
    type: 'movie',
    title: 'Afterlight',
    year: 2024,
    rating: '8.3',
    runtime: '1h 59m',
    duration: 119,
    genres: ['Drama', 'Mystery'],
    maturity: '16+',
    poster: '/art/poster-afterlight.jpg',
    backdrop: '/art/poster-afterlight.jpg',
    synopsis: 'A late-night train, a city in motion, and a conversation that changes the way one man remembers his past.',
    director: 'Mara Bell',
    cast: ['Darius Cole', 'Nina Tran', 'Sol Reyes', 'Evan Brooks'],
    badge: 'AWARD WINNER',
  },
  {
    id: 'northbound',
    type: 'series',
    title: 'Northbound',
    year: 2026,
    rating: '9.0',
    runtime: '2 Seasons',
    duration: 47,
    genres: ['Mystery', 'Drama', 'Thriller'],
    maturity: '16+',
    poster: '/art/poster-northbound.jpg',
    backdrop: '/art/poster-northbound.jpg',
    synopsis: 'Two estranged siblings return to the mountain town they left behind. As the snow settles in, an old disappearance begins to unravel.',
    director: 'R. I. Mercer',
    cast: ['Leah Carter', 'Caleb Wright', 'Sora Kim', 'Mason Reed'],
    badge: 'NEW EPISODES FRIDAY',
    seasons: 2,
  },
  {
    id: 'the-wild-within',
    type: 'series',
    title: 'The Wild Within',
    year: 2025,
    rating: '8.7',
    runtime: '1 Season',
    duration: 52,
    genres: ['Documentary', 'Nature'],
    maturity: 'All',
    poster: '/art/poster-quiet-earth.jpg',
    backdrop: '/art/poster-quiet-earth.jpg',
    synopsis: 'Across the last untouched wildernesses, the smallest lives make the biggest journeys. An intimate portrait of a world on the edge of change.',
    director: 'Celia Ward',
    cast: ['Narrated by Samira Hale'],
    badge: 'VEYRA DOCUMENTARY',
    seasons: 1,
  },
  {
    id: 'the-deep-blue',
    type: 'series',
    title: 'The Deep Blue',
    year: 2024,
    rating: '8.2',
    runtime: '3 Seasons',
    duration: 44,
    genres: ['Drama', 'Adventure'],
    maturity: '13+',
    poster: '/art/poster-saltline.jpg',
    backdrop: '/art/poster-saltline.jpg',
    synopsis: 'On a remote research vessel, a small crew maps the sea floor and the fault lines running beneath their own lives.',
    director: 'Inez Navarro',
    cast: ['Maya Reid', 'Kenji Ito', 'Ava Brooks', 'Julian Park'],
    badge: '3 SEASONS',
    seasons: 3,
  },
  {
    id: 'small-hours',
    type: 'movie',
    title: 'Small Hours',
    year: 2025,
    rating: '7.8',
    runtime: '1h 42m',
    duration: 102,
    genres: ['Drama', 'Romance'],
    maturity: '13+',
    poster: '/art/poster-blue-hour.jpg',
    backdrop: '/art/poster-blue-hour.jpg',
    synopsis: 'Over the course of a summer, an old bookshop and the people who pass through it become a second home for a young musician.',
    director: 'Mira Laurent',
    cast: ['Jo Park', 'Elise Martin', 'Rafi Flores', 'Noor Patel'],
    badge: 'A QUIET FAVORITE',
  },
  {
    id: 'mile-marker',
    type: 'movie',
    title: 'Mile Marker',
    year: 2026,
    rating: '7.8',
    runtime: '1h 51m',
    duration: 111,
    genres: ['Action', 'Thriller'],
    maturity: '16+',
    poster: '/art/poster-mile-marker.jpg',
    backdrop: '/art/poster-mile-marker.jpg',
    synopsis: 'One last drive across the desert turns into a race against a past that refuses to stay in the rear-view mirror.',
    director: 'D. K. Rowe',
    cast: ['Imani Cole', 'Lucas Tan', 'Vicente Ruiz', 'Jess Lane'],
    badge: 'NEW RELEASE',
  },
  {
    id: 'good-company',
    type: 'movie',
    title: 'Good Company',
    year: 2025,
    rating: '8.0',
    runtime: '1h 46m',
    duration: 106,
    genres: ['Comedy', 'Drama'],
    maturity: '13+',
    poster: '/art/poster-good-company.jpg',
    backdrop: '/art/poster-good-company.jpg',
    synopsis: 'Four old friends make a pact to meet for dinner every week. No one said they had to tell the whole truth.',
    director: 'Jules Bennett',
    cast: ['Tess Morgan', 'Reggie James', 'Ari Patel', 'Mina Duval'],
    badge: 'A LITTLE LEVITY',
  },
  {
    id: 'paper-atlas',
    type: 'series',
    title: 'The Paper Atlas',
    year: 2026,
    rating: '8.9',
    runtime: '1 Season',
    duration: 24,
    genres: ['Anime', 'Fantasy', 'Adventure'],
    maturity: 'All',
    poster: '/art/poster-paper-atlas.jpg',
    backdrop: '/art/poster-paper-atlas.jpg',
    synopsis: 'A young mapmaker discovers a moving library above the clouds — and a story that can redraw the world below.',
    director: 'Keiko Mori',
    cast: ['Voices by Yuna Sato', 'Ren Ito', 'Mika Vale', 'Sora Kim'],
    badge: 'ANIMATED SERIES',
    seasons: 1,
  },
  {
    id: 'strange-water',
    type: 'series',
    title: 'Strange Water',
    year: 2026,
    rating: '8.1',
    runtime: '1 Season',
    duration: 46,
    genres: ['Mystery', 'Thriller', 'Drama'],
    maturity: '16+',
    poster: '/art/poster-saltline.jpg',
    backdrop: '/art/poster-saltline.jpg',
    synopsis: 'After an impossible signal surfaces in the harbour, a night-shift diver begins finding traces of a town that was never on any map.',
    director: 'Inez Navarro',
    cast: ['Sofia Nordin', 'Milo James', 'Tara Wells', 'Eli Park'],
    badge: 'NEW SERIES',
    seasons: 1,
  },
  {
    id: 'thin-air',
    type: 'series',
    title: 'Thin Air',
    year: 2026,
    rating: '8.4',
    runtime: '1 Season',
    duration: 49,
    genres: ['Sci-Fi', 'Mystery'],
    maturity: '13+',
    poster: '/art/poster-last-signal.jpg',
    backdrop: '/art/hero-last-signal.jpg',
    synopsis: 'A weather station at the top of the world receives a message from a crew that vanished thirty years ago.',
    director: 'Ana Velasquez',
    cast: ['Arun Shah', 'Maeve Lin', 'Jonah Hale', 'Iris Beck'],
    badge: 'SEASON 1',
    seasons: 1,
  },
];

export const titleById = Object.fromEntries(titles.map((title) => [title.id, title]));
export const movies = titles.filter((title) => title.type === 'movie');
export const series = titles.filter((title) => title.type === 'series');

const episode = (id, number, name, runtime, description, progress = 0) => ({
  id,
  number,
  name,
  runtime,
  description,
  progress,
  watched: progress >= 100,
  thumbnail: '/art/poster-northbound.jpg',
});

export const seasons = {
  northbound: {
    1: [
      episode('nb-s1e1', 'S01E01', 'The Road Back', '48 min', 'A winter storm forces two estranged siblings to return to the town they swore to leave.', 100),
      episode('nb-s1e2', 'S01E02', 'White Noise', '46 min', 'A signal on an old frequency brings a forgotten night back into focus.', 100),
      episode('nb-s1e3', 'S01E03', 'The Long Way', '51 min', 'Mara follows a trail past the tree line, while Eli tries to keep the town calm.', 100),
      episode('nb-s2e4', 'S02E04', 'Where the Snow Ends', '47 min', 'The thaw reveals a clue beneath the old bridge. Mara knows exactly where it leads.', 62),
      episode('nb-s2e5', 'S02E05', 'A Familiar Shape', '49 min', 'A visitor arrives before sunrise with a story no one wants to hear.', 0),
      episode('nb-s2e6', 'S02E06', 'The Quiet Between', '52 min', 'The siblings must choose which truth to carry home.', 0),
    ],
    2: [
      episode('nb-s2e1', 'S02E01', 'First Snow', '50 min', 'The first storm of the season arrives early, along with a name from the past.'),
      episode('nb-s2e2', 'S02E02', 'Low Country', '45 min', 'A search along the river sends Eli back to the family cabin.'),
      episode('nb-s2e3', 'S02E03', 'The Line', '48 min', 'Mara follows an old map toward the northern ridge.'),
      episode('nb-s2e4b', 'S02E04', 'Where the Snow Ends', '47 min', 'The thaw reveals a clue beneath the old bridge. Mara knows exactly where it leads.', 62),
      episode('nb-s2e5b', 'S02E05', 'A Familiar Shape', '49 min', 'A visitor arrives before sunrise with a story no one wants to hear.'),
    ],
  },
  'the-wild-within': {
    1: [
      { ...episode('ww-s1e1', 'S01E01', 'A World Apart', '52 min', 'In the first light, the forest wakes one tiny life at a time.'), thumbnail: '/art/poster-quiet-earth.jpg' },
      { ...episode('ww-s1e2', 'S01E02', 'The Great Migration', '49 min', 'A journey across open country becomes a matter of survival.'), thumbnail: '/art/poster-saltline.jpg' },
      { ...episode('ww-s1e3', 'S01E03', 'After the Rain', '54 min', 'The smallest creatures thrive in a landscape transformed by water.'), thumbnail: '/art/poster-quiet-earth.jpg' },
    ],
  },
  'the-deep-blue': {
    1: [
      { ...episode('db-s1e1', 'S01E01', 'First Light', '44 min', 'A new crew begins a survey in waters no one has mapped.'), thumbnail: '/art/poster-saltline.jpg' },
      { ...episode('db-s1e2', 'S01E02', 'Pressure', '46 min', 'A storm pushes the crew to make a difficult call.'), thumbnail: '/art/poster-afterlight.jpg' },
      { ...episode('db-s1e3', 'S01E03', 'The Sound Below', '43 min', 'A strange acoustic signature leads to a discovery.'), thumbnail: '/art/poster-blue-hour.jpg' },
    ],
  },
  'paper-atlas': {
    1: [
      { ...episode('pa-s1e1', 'S01E01', 'The Map That Moved', '24 min', 'Nori finds a new island drawn in the margin of a very old book.'), thumbnail: '/art/poster-paper-atlas.jpg' },
      { ...episode('pa-s1e2', 'S01E02', 'Above the Weather', '23 min', 'The library ship rises into the clouds, just as the map said it would.'), thumbnail: '/art/poster-quiet-earth.jpg' },
      { ...episode('pa-s1e3', 'S01E03', 'A Borrowed Compass', '25 min', 'A compass with a mind of its own points toward a forgotten sky.'), thumbnail: '/art/poster-paper-atlas.jpg' },
    ],
  },
  'strange-water': {
    1: [
      { ...episode('sw-s1e1', 'S01E01', 'The Sounding', '46 min', 'A late-night call sends a harbour diver beneath the pier, where the water is warmer than it should be.'), thumbnail: '/art/poster-saltline.jpg' },
      { ...episode('sw-s1e2', 'S01E02', 'Below the Line', '43 min', 'A familiar voice comes through the radio from a depth no one can reach.'), thumbnail: '/art/poster-afterlight.jpg' },
      { ...episode('sw-s1e3', 'S01E03', 'Low Tide', '49 min', 'The town begins to remember something it agreed to forget.'), thumbnail: '/art/poster-blue-hour.jpg' },
    ],
  },
  'thin-air': {
    1: [
      { ...episode('ta-s1e1', 'S01E01', 'Zero Visibility', '49 min', 'A routine shift at the edge of the world becomes anything but routine.'), thumbnail: '/art/poster-last-signal.jpg' },
      { ...episode('ta-s1e2', 'S01E02', 'Dead Frequency', '47 min', 'The station hears its first reply.'), thumbnail: '/art/hero-last-signal.jpg' },
      { ...episode('ta-s1e3', 'S01E03', 'Long Night', '51 min', 'The crew traces a signal through the oldest ice.'), thumbnail: '/art/poster-quiet-earth.jpg' },
    ],
  },
};

export const railData = {
  continue: ['northbound', 'last-signal', 'blue-hour', 'the-wild-within'],
  trending: ['quiet-earth', 'saltline', 'northbound', 'blue-hour', 'last-signal', 'afterlight'],
  popularMovies: ['last-signal', 'blue-hour', 'quiet-earth', 'mile-marker', 'good-company', 'saltline', 'afterlight', 'small-hours'],
  popularSeries: ['northbound', 'strange-water', 'paper-atlas', 'the-wild-within', 'the-deep-blue', 'thin-air'],
  because: ['afterlight', 'small-hours', 'good-company', 'saltline', 'blue-hour'],
  newReleases: ['last-signal', 'mile-marker', 'paper-atlas', 'blue-hour', 'northbound', 'the-deep-blue'],
  topRated: ['northbound', 'quiet-earth', 'paper-atlas', 'the-wild-within', 'afterlight', 'last-signal'],
};

export const watchProgress = {
  northbound: { percent: 62, label: 'S02E04 · Where the Snow Ends', remaining: '18 min left', episode: 'nb-s2e4' },
  'last-signal': { percent: 41, label: 'Movie', remaining: '1h 14m left' },
  'the-wild-within': { percent: 78, label: 'S01E02 · The Great Migration', remaining: '11 min left', episode: 'ww-s1e2' },
  'blue-hour': { percent: 24, label: 'Movie', remaining: '1h 27m left' },
};

export const initialHistory = [
  { id: 'northbound', date: 'Today · 8:42 PM', detail: 'S02E04 · Where the Snow Ends', percent: 62, episode: 'nb-s2e4' },
  { id: 'last-signal', date: 'Yesterday · 9:16 PM', detail: 'Movie', percent: 41 },
  { id: 'the-wild-within', date: 'Yesterday · 6:04 PM', detail: 'S01E02 · The Great Migration', percent: 78, episode: 'ww-s1e2' },
  { id: 'blue-hour', date: 'Mon · 10:38 PM', detail: 'Movie', percent: 24 },
];

export const initialDownloads = [
  { id: 'blue-hour', quality: '1080p', progress: 78, status: 'downloading', paused: false, size: '2.1 GB' },
  { id: 'quiet-earth', quality: '720p', progress: 100, status: 'complete', paused: false, size: '1.4 GB' },
];

export const initialNotifications = [
  { id: 'n1', kind: 'episode', title: 'Northbound is back.', body: 'A new episode is ready when you are.', time: '2 hours ago', unread: true, poster: '/art/poster-northbound.jpg', contentId: 'northbound' },
  { id: 'n2', kind: 'release', title: 'A new release for you.', body: 'The Quiet Earth is now streaming.', time: 'Yesterday', unread: true, poster: '/art/poster-quiet-earth.jpg', contentId: 'quiet-earth' },
  { id: 'n3', kind: 'recommendation', title: 'Picked for a slow Sunday.', body: 'Blue Hour feels right for tonight.', time: '3 days ago', unread: false, poster: '/art/poster-blue-hour.jpg', contentId: 'blue-hour' },
];

export const genres = ['All', 'Action', 'Comedy', 'Drama', 'Mystery', 'Sci-Fi', 'Thriller', 'Documentary', 'Romance', 'Nature'];
